[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor = "HyojGUP4kXbK42sPr9DAe1rDCnnYp4JPgzvXbG78kmUd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=a2488320-5767-4074-8bfe-8eda86de12f3"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
