import { NextApiRequest, NextApiResponse } from 'next';
import prisma from '../../../lib/prisma';
import crypto from 'crypto';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    if (req.method !== 'POST') return res.status(405).json({ error: "Method not allowed" });

    const { walletAddress, code } = req.body;

    if (!walletAddress || !code) {
        return res.status(400).json({ error: "Missing data" });
    }

    try {
        // 1. Find the recruiter by the code
        const recruiter = await prisma.user.findUnique({
            where: { referralCode: code.toUpperCase() }
        });

        if (!recruiter) {
            return res.status(404).json({ error: "This referral code was not generated by our system." });
        }

        // 2. CRYPTOGRAPHIC VERIFICATION
        const secret = process.env.REFERRAL_SECRET || 'default_secret_change_me';
        const expectedHash = crypto
            .createHmac('sha256', secret)
            .update(recruiter.walletAddress)
            .digest('hex')
            .substring(0, 6)
            .toUpperCase();

        const expectedFullCode = `LAAM-${expectedHash}-TAG`;

        if (code.toUpperCase() !== expectedFullCode) {
            return res.status(400).json({ error: "Invalid code signature detected." });
        }

        // 3. Check for self-referral
        if (recruiter.walletAddress === walletAddress) {
            return res.status(400).json({ error: "Self-referral is prohibited." });
        }

        // 4. Check if user already has a referrer
        const user = await prisma.user.findUnique({
            where: { walletAddress },
            select: { referredBy: true }
        });

        if (user?.referredBy) {
            return res.status(400).json({ error: "Referral already applied." });
        }

        // 5. Atomic Update: Link user, Increment Progress (10%), and handle Milestone
        await prisma.$transaction(async (tx) => {
            // Link the new user
            await tx.user.update({
                where: { walletAddress },
                data: { referredBy: recruiter.walletAddress }
            });

            // Calculate new progress
            const currentProgress = recruiter.referralProgress + 10;
            const newClaims = Math.floor(currentProgress / 100);
            const remainingProgress = currentProgress % 100;

            // Update recruiter
            await tx.user.update({
                where: { walletAddress: recruiter.walletAddress },
                data: {
                    referralProgress: remainingProgress,
                    claimableRewards: { increment: newClaims }
                }
            });

            // Log the activity
            await tx.activity.create({
                data: {
                    userId: recruiter.walletAddress,
                    type: "RECRUIT_JOIN",
                    asset: "PROGRESS",
                    amount: 10,
                }
            });
        });

        return res.status(200).json({
            success: true,
            recruiter: recruiter.username || recruiter.walletAddress
        });
    } catch (error) {
        console.error(error);
        return res.status(500).json({ error: "Failed to verify referral." });
    }
}